### ISSUE TITLE
$UCN not available on Uniswap Info

### ISSUE THREAD

**Issue by unicommaster** [Uniswap/uniswap-org#105]
We are building an unofficial community of Uniswap.

We never claimed as an official community of yours, but we are creating an unofficial community behind.

Can I know the reason why the UNC/ETH pair vanished on Uniswap Info?

Heres the contract address.

https://etherscan.io/address/0x7cdb719aa9d079da0be147495a197bd39be6e7c9

**Comment by callil** [comment]
Wrong repo - try the uniswap-info repository
