### ISSUE TITLE
Dead link to pair-addresses explanation

### ISSUE THREAD

**Issue by kronrod** [Uniswap/uniswap-org#132]
The page https://uniswap.org/docs/v2/SDK/pair/ mentions a method "getAddress" that does not exist in the Pair contract and links to https://uniswap.org/docs/v2/technical-considerations/pair-addresses, which does not exist either.

Probably, this section should better refer to the pairFor function from
https://github.com/Uniswap/uniswap-v2-periphery/blob/master/contracts/libraries/UniswapV2Library.sol
and maybe link to 
https://docs.openzeppelin.com/cli/2.8/deploying-with-create2
for those who want to know what CREATE2 does.

**Comment by ebonetti** [comment]
From webarchive seems it [never existed in the first place](https://web.archive.org/web/*/https://uniswap.org/docs/v2/technical-considerations/pair-addresses). Maybe a target within uniswap docs could be [https://uniswap.org/docs/v2/smart-contract-integration/getting-pair-addresses/ ](https://uniswap.org/docs/v2/smart-contract-integration/getting-pair-addresses/ ).

Actually there are [more references](https://github.com/Uniswap/uniswap-org/search?q=%2Fdocs%2Fv2%2Ftechnical-considerations%2F&type=Code) to this non existent `technical-consideration` subfolder, which then turn into broken links in the docs.

**Comment by callil** [comment]
I think I cleaned these up in the latest. Let me know if you find more issues.
