### ISSUE TITLE
Spelling error in docs/v2/advanced-topics/fees/

### ISSUE THREAD

**Issue by iwearahoodie** [Uniswap/uniswap-org#145]
**Bug Description**
At [https://uniswap.org/docs/v2/advanced-topics/fees/](https://uniswap.org/docs/v2/advanced-topics/fees/)

second paragraph reads 
"...tokens to remove a **porportional** share of the underlying..."

should read: _proportional_

**Steps to Reproduce**
1. Be born.
2. Learn to read.
3. Buy a computer. 
4. Connect to the internet
5. Open a web browser
6. Visit https://uniswap.org/docs/v2/advanced-topics/fees/
7. Read second paragraph. 

**Expected Behavior**
idk I actually expect occasional spelling errors it's not like a big deal or anything. 

**Additional Context**
I'm lacking sleep.

**Comment by callil** [comment]
Good catch thanks!
