### ISSUE TITLE
The value of tokenA in how-uniswap-works page is wrong.

### ISSUE THREAD

**Issue by guce** [Uniswap/uniswap-org#174]
src/pages/docs/v2/01-protocol-overview/01-how-uniswap-works.md

In the two trade graphs, the number of tokenA should be 1203 and 1203.03, not 1210

**Comment by callil** [comment]
fixed in https://github.com/Uniswap/uniswap-org/commit/eb366f611f1eff4f821322514ed326f01eb885fb
