### ISSUE TITLE
Uncaught TypeError: Cannot set property 'autoRefreshOnNetworkChange' of undefined

### ISSUE THREAD

**Issue by ligi** [Uniswap/uniswap-org#232]
If there is no MetaMask installed one gets:

![Selection_445](https://user-images.githubusercontent.com/111600/106366546-e53b7a00-633c-11eb-986c-ed52613de528.png)

I would either expect some helpful error message instead of a white screen. Or ideally not relying on an installed MetaMask in the first place - especially as better options like MetaMask are supported.

**Comment by moodysalem** [comment]
This issue already exists in the uniswap-interface repository

**Comment by ligi** [comment]
Ah lol - and I even opened it there last year - totally forgot about this. But there you asked me a question but I cannot answer as it is locked:

![Selection_453](https://user-images.githubusercontent.com/111600/106390153-47e95000-63e7-11eb-9991-51619a6f3490.png)

https://github.com/Uniswap/uniswap-interface/issues/1214
