### ISSUE TITLE
Launch help.uniswap.org 

### ISSUE THREAD

**Issue by willhennessy** [Uniswap/uniswap-org#286]
We've created an Intercom site at https://intercom.help/uniswap/en/ and are populating content.

By Tuesday we want to set up a custom domain at **help.uniswap.org**

Intercom provides [instructions](https://developers.intercom.com/installing-intercom/docs/set-up-your-custom-domain?showHidden=f2cb6)
1. DONE - I have entered the info in Intercom settings
<img width="555" alt="Screen Shot 2021-07-08 at 12 11 29 AM" src="https://user-images.githubusercontent.com/5455577/124861195-0c981200-df81-11eb-90b3-83d8732178aa.png">

2. Create a custom CNAME record in uniswap.org DNS to enable help.uniswap.org
3. Configure SSL

Can you tackle steps 2 and 3 by Monday mid-day? Let me know if the Intercom instructions aren't clear!

**Comment by moodysalem** [comment]
mapped help.uniswap.org to custom.intercom.help
