### ISSUE TITLE
uniswap exchange problem

### ISSUE THREAD

**Issue by ROACHREEL** [Uniswap/uniswap-org#33]
I am trying to swap eth for stable coin data, but I annot get it to swap when I hit the swap button. Any help

**Comment by kaywarra** [comment]
same here  have used before no probs .now no action at all

**Comment by ROACHREEL** [comment]
who can help us with this? I think when I entered the password somehow I hit a bad key or entered a error so now I am not able to get pass the password. So my questions are #1 can I add a wallet and transfer the balance of the first wallet to the second ? Or can the first wallet balance be sent back to Coinbase where it came from? Or is there a way to change the password somehow?
