### ISSUE TITLE
Coin not showing up in find

### ISSUE THREAD

**Issue by sting-fancy** [Uniswap/uniswap-org#35]
From
https://hexdex.win/swap
I tried both android wallet apps, which redirects to
https://uniswap.exchange/swap
With the inbuilt browser

But the 'Output' coin is blank. (no Hex) 
When trying to search in the Output coin, no results are found for 'HEX'.

I am trying to swap ETH in my wallet for HEX.

**Comment by callil** [comment]
Wrong repository - try https://github.com/Uniswap/uniswap-frontend/issues
