### ISSUE TITLE
Lost $100, ETH - DATA swap is not showing up in my Portis wallet

### ISSUE THREAD

**Issue by nitinarora135** [Uniswap/uniswap-org#40]
I lost my $100 worth ETH. Please help me get my money back. please contact me at aroraknitin@gmail.com
DATA tokens never received to my wallet.

Steps:
1. Connected Portis wallet to Uniswap
2. Selected ETH as input and DATA as output.
3. performed the swap.

Transaction hash:
0x03c6eaecadd8d778970b42e1d5b682ff41cf8ee09f9306e6db9748603a8061b8

email: aroraknitin@gmail.com
phone: +1 650 931 5658

**Comment by kitchenkup** [comment]
any answer?   I was taken for $165

**Comment by callil** [comment]
This is a repository for the uniswap protocol website. I recommend you join the community discord to discuss trades.
