### ISSUE TITLE
Unable to withdraw liquidity from user added exchange

### ISSUE THREAD

**Issue by ArtOfCrypto** [Uniswap/uniswap-org#41]
I recently added (2.2821 ETH) and (1,066,762.74 SENT) to the ETH/SENT pool in exchange for (7.0684 UNI-V1).

In etherscan, I see the related UNI-V1 tokens is in my MetaMask wallet, and the associated contract (0x0b5ce6f7cbe0627aa8ad2e7e69ed554c0fe79162) appears to have the appropriate funds.

**The issue arises when I attempt to exchange the 7 UNI-V1 tokens with "the remove liquidity function" in UniSwap. The button does not start a MetaMask transaction.**  

Other pools such as ETH-LINK and ETH-UBT, appear to we functioning as expected for me.

Thank you for your time.

**Comment by callil** [comment]
This is a repository for the uniswap protocol website. I recommend you join the community discord to discuss trades.
