### ISSUE TITLE
uniswap jacked me

### ISSUE THREAD

**Issue by kitchenkup** [Uniswap/uniswap-org#42]
ETH to HEX on Uniswap exchange annnd now Im a $165 in the hole from one transaction.  why was it so much?  also From Meta mask last night a pretty significant loss from exchanging the same token.  please advise.

hash from tonight

0x6d475b182ff45cfb1c95e3f18187e504ed829e4cce5048f4c99a4077046b7a11

**Comment by callil** [comment]
This is a repository for the uniswap protocol website. I recommend you join the community discord to discuss trades.
