### ISSUE TITLE
Request for docs: how-to-guide for getting price w v2 sdk

### ISSUE THREAD

**Issue by bohendo** [Uniswap/uniswap-org#71]
We're using the uniswap v1 sdk to get some price info in our app using something like:

```
const price = getMarketDetails(
  await getTokenReserves(fromTokenAddress),
  await getTokenReserves(toTokenAddress),
).marketRate.rate;
```

I was hoping to be able to visit the docs to figure out a similar way to get price info w the v2 sdk.. But the solution is not obvious.

Uniswap doubling as a price oracle is one of the most exciting features of the v2 upgrade & I suspect is the most common reason for devs to visit the v2 sdk docs.

The docs are not clear right now and I'm currently having trouble understanding how to proceed. This issue isn't to ask for help w this specific problem, I can continue reading the docs & figure out how all the pieces fit together & leave a comment w the solution I find.

But there should be a simple code snippet (like I provided above for v1) and just a few sentences explaining what it does that's easy to find for devs like me that just want to get something working quickly.

**Comment by callil** [comment]
@bohendo There are a new set of docs! check out beta.uniswap.org. Let me know if that helps!
https://beta.uniswap.org/docs/v2/javascript-SDK/pricing/

**Comment by bohendo** [comment]
Ahh the docs you linked to are perfect, thank you :pray:
